name: reviewdog on Pull Request

on: [pull_request]

jobs:

   misspell:
    name: runner / misspell
    runs-on: ubuntu-latest

    steps:
      - name: Check out code.
        uses: actions/checkout@master
      - name: misspell
        uses: reviewdog/action-misspell@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "US"
