name: reviewdog on Pull Request

on: [push] # on: [pull_request]

jobs:
   reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest

    steps:
      - name: Check out code.
        uses: actions/checkout@v1

      - name: Download Gradle dependencies
        run: ./gradlew dependencies

      - name: Run detekt
        run: ./gradlew detekt

      - name: Setup reviewdog
        run: |
          mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
          echo ::add-path::$HOME/bin

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         cat app/build/reports/detekt/detekt.xml | reviewdog -f=checkstyle -name="linter-name (detekt)" -reporter=github-check

   misspell:
    name: runner / misspell
    runs-on: ubuntu-latest

    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
